#!/bin/bash

# esecuzione della sintesi
./total_synt.sh
echo "- This file are generated by synopsys:
		synt/synt_out/compilexx.txt
		synt/synt_out/report_timingxx.txt
		synt/synt_out/report_area.txt
		netlist/top_entity.sdf
		netlist/top_entity.sdc
		netlist/top_enetity.v

"
# esecution of netlist
cd ../sim
./sim_saif.sh
echo "- This file are generated by modelsim
		vcd/top_entity.vcd
		saif/top_entity.saif
		
"

# potenza finale
cd ../synt
source /software/scripts/init_synopsys_64.18
dc_shell -f final_power.scr >> ./synt_out/dc_shell_output.txt
echo "- This file are generated by synopsys
		synt_out/report_power_final.txt

"

