#!/bin/bash
source $BASHLIB

if [[ $# < 1 ]]; then
	echo "Error, dammi almeno il periodo di clock"
	exit
fi

t=$1
t_ext="_$(echo $t | tr "." "d")"
arch="csa"
if [[ $# > 1 ]]; then
	t_ext=$(echo "$t_ext$2")
fi
if [[ $# > 2 ]]; then
	arch=$3
else
	arch="noarch"
fi
echo $arch

# esecuzione della sintesi
./total_synt.sh $t $t_ext $arch
echo "- This file are generated by synopsys:
        synt/synt_out/compilexx.txt
        synt/synt_out/report_timingxx.txt
        synt/synt_out/report_area.txt
        netlist/top_entity.sdf
        netlist/top_entity.sdc
        netlist/top_enetity.v

"

